# Generated by Django 2.1.1 on 2019-07-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_address', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField()),
                ('emp_contact_no', models.IntegerField()),
            ],
        ),
    ]
